language: go
env:
  - GO111MODULE=on
go:
  - 1.2
  - 1.3
  - 1.4
  - tip
install:
  - go build .
script:
  - golint -set_exit_status ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
