# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
go_import_path: github.com/zerjioang/etherniti
sudo: false

# required to be able to generate docker images
# needed for the docker pipe
services:
  - 'docker'

language: go
addons:
  apt:
    packages:
    # for binary packing
      - upx

env:
  - HOME=/home/travis GOPATH=$HOME/gopath GOBIN=$GOPATH/bin

cache:
  directories:
    - ~/.cache/go-build
    - ~/gopath/pkg/mod

# Only the last two Go releases are supported by the Go team with security
# updates. Any older versions be considered deprecated. Don't bother testing
# with them.
go:
  - 1.11.x
  - tip

# Only clone the most recent commit.
git:
depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

before_install:
  - ./ci/before_install.sh
install:
  - ./ci/install.sh
before_script:
  - ./ci/before_script.sh
# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - ./ci/script.sh
after_script:
  - ./ci/after_script.sh
after_success:
  - ./ci/after_success.sh
before_deploy:
  - ./ci/before_deploy.sh
deploy:
  provider: script
  script: ./ci/deploy.sh
  on:
    branch: master

ssh_known_hosts: github.com
