# 
# Copyright Etherniti. All Rights Reserved.
# SPDX-License-Identifier: Apache 2
# 

FROM preloader:latest as compiler

MAINTAINER team@etherniti.org

LABEL IMAGE etherniti-api
LABEL PROJECT etherniti

ENV BASE /go/src/github.com/zerjioang/etherniti
ENV BUILD_MODE prod
ENV FILE proxy
ENV ETHERNITI_GOOS linux
ENV ETHERNITI_GOARCH amd64
ENV USER etherniti

# add source code to docker image for multistage build
WORKDIR $BASE
COPY . $BASE

# optimize code for production compilation
# RUN echo "Preparing code for production deployment" && ./scripts/prepare_production.sh

# Create user $USER and compile
RUN adduser --system --no-create-home --gecos 'Etherniti user' --disabled-password -q ${USER} && \
    ./scripts/dep.sh && \
    ./scripts/docker/compile_build.sh && \
    rm -rf .git && \
    chmod +rwx $FILE && \
    chown $USER $FILE && \
    upx -9 -v $FILE

# BEGIN: install modified version of glibc
FROM alpine:latest
ENV LANG=C.UTF-8

# Here we install GNU libc (aka glibc) and set C.UTF-8 locale as default.
RUN ALPINE_GLIBC_BASE_URL="https://github.com/sgerrand/alpine-pkg-glibc/releases/download" && \
    ALPINE_GLIBC_PACKAGE_VERSION="2.27-r0" && \
    ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    apk add --no-cache --virtual=.build-dependencies wget ca-certificates && \
    wget \
        "https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub" \
        -O "/etc/apk/keys/sgerrand.rsa.pub" && \
    wget \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" && \
    apk add --no-cache \
        "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" && \
    \
    rm "/etc/apk/keys/sgerrand.rsa.pub" && \
    /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 "$LANG" || true && \
    echo "export LANG=$LANG" > /etc/profile.d/locale.sh && \
    \
    apk del glibc-i18n && \
    rm "/root/.wget-hsts" && \
    apk del .build-dependencies && \
    rm \
        "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"

# END: install modified version of glibc

ENV X_ETHERNITI_INTERACTION_PORT            8080 4430
ENV USER                                    etherniti
ENV GOPATH                                  /home/${USER}/go

WORKDIR /home/${USER}

# Create user $USER and resources folder
RUN adduser -S ${USER} && mkdir -p $GOPATH/src/github.com/zerjioang/etherniti/resources

COPY --from=compiler /go/src/github.com/zerjioang/etherniti/proxy           proxy
COPY --from=compiler /etc/ssl/certs/ca-certificates.crt                     /etc/ssl/certs/
# copy proxy resource files
COPY --from=compiler /go/src/github.com/zerjioang/etherniti/resources/root     $GOPATH/src/github.com/zerjioang/etherniti/resources/root
COPY --from=compiler /go/src/github.com/zerjioang/etherniti/resources/swagger  $GOPATH/src/github.com/zerjioang/etherniti/resources/swagger

ENTRYPOINT ["./proxy"]
EXPOSE $X_ETHERNITI_INTERACTION_PORT

# change to non root user for execution
USER ${USER}
