[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.8"

[[constraint]]
  name = "github.com/labstack/gommon"
  version = "0.2.8"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[prune]
  go-tests = true
  unused-packages = true
