package api

const (
	HttpProfileHeaderkey = "X-Metw-Profile"
)

var (
	badBotsList = []string{
		"almaden",
		"^Anarchie",
		"^ASPSeek",
		"^attach",
		"^autoemailspider",
		"^BackWeb",
		"^Bandit",
		"^BatchFTP",
		"^BlackWidow",
		"^Bot mailto:craftbot@yahoo.com",
		"^Buddy",
		"^bumblebee",
		"^CherryPicker",
		"^ChinaClaw",
		"^CICC",
		"^Collector",
		"^Copier",
		"^Crescent",
		"^Custo",
		"^DA",
		"^DIIbot",
		"^DISCo",
		"^DISCo Pump",
		"^Download Demon",
		"^Download Wonder",
		"^Downloader",
		"^Drip",
		"^DSurf15a",
		"^eCatch",
		"^EasyDL/2.99",
		"^EirGrabber",
		"email",
		"^EmailCollector",
		"^EmailSiphon",
		"^EmailWolf",
		"^Express WebPictures",
		"^ExtractorPro",
		"^EyeNetIE",
		"^FileHound",
		"^FlashGet",
		"FrontPage",
		"^GetRight",
		"^GetSmart",
		"^GetWeb!",
		"^gigabaz",
		"^Go\\!Zilla",
		"^Go!Zilla",
		"^Go-Ahead-Got-It",
		"^gotit",
		"^Grabber",
		"^GrabNet",
		"^Grafula",
		"^grub-client",
		"^HMView",
		"^HTTrack",
		"^httpdown",
		".*httrack.*",
		"^ia_archiver",
		"^Image Stripper",
		"^Image Sucker",
		"^Indy*Library",
		"Indy Library",
		"^InterGET",
		"^InternetLinkagent",
		"^Internet Ninja",
		"^InternetSeer.com",
		"^Iria",
		"^JBH*agent",
		"^JetCar",
		"^JOC Web Spider",
		"^JustView",
		"^larbin",
		"^LeechFTP",
		"^LexiBot",
		"^lftp",
		"^Link*Sleuth",
		"^likse",
		"^Link",
		"^LinkWalker",
		"^Mag-Net",
		"^Magnet",
		"^Mass Downloader",
		"^Memo",
		"^Microsoft.URL",
		"^MIDown tool",
		"^Mirror",
		"^Mister PiX",
		"^Mozilla.*Indy",
		"^Mozilla.*NEWT",
		"^Mozilla*MSIECrawler",
		"^MS FrontPage*",
		"^MSFrontPage",
		"^MSIECrawler",
		"^MSProxy",
		"^Navroad",
		"^NearSite",
		"^NetAnts",
		"^NetMechanic",
		"^NetSpider",
		"^Net Vampire",
		"^NetZIP",
		"^NICErsPRO",
		"^Ninja",
		"^Octopus",
		"^Offline Explorer",
		"^Offline Navigator",
		"^Openfind",
		"^PageGrabber",
		"^Papa Foto",
		"^pavuk",
		"^pcBrowser",
		"^Ping",
		"^PingALink",
		"^Pockey",
		"^psbot",
		"^Pump",
		"^QRVA",
		"^RealDownload",
		"^Reaper",
		"^Recorder",
		"^ReGet",
		"^Scooter",
		"^Seeker",
		"^Siphon",
		"^sitecheck.internetseer.com",
		"^SiteSnagger",
		"^SlySearch",
		"^SmartDownload",
		"^Snake",
		"^SpaceBison",
		"^sproose",
		"^Stripper",
		"^Sucker",
		"^SuperBot",
		"^SuperHTTP",
		"^Surfbot",
		"^Szukacz",
		"^tAkeOut",
		"^Teleport Pro",
		"^URLSpiderPro",
		"^Vacuum",
		"^VoidEYE",
		"^Web Image Collector",
		"^Web Sucker",
		"^WebAuto",
		"^[Ww]eb[Bb]andit",
		"^webcollage",
		"^WebCopier",
		"^Web Downloader",
		"^WebEMailExtrac.*",
		"^WebFetch",
		"^WebGo IS",
		"^WebHook",
		"^WebLeacher",
		"^WebMiner",
		"^WebMirror",
		"^WebReaper",
		"^WebSauger",
		"^Website",
		"^Website eXtractor",
		"^Website Quester",
		"^Webster",
		"^WebStripper",
		"WebWhacker",
		"^WebZIP",
		"^Wget",
		"^Whacker",
		"^Widow",
		"^WWWOFFLE",
		"^x-Tractor",
		"^Xaldon WebSpider",
		"^Xenu",
		"^Zeus.*Webster",
		"^Zeus",
		//literal strings
		"Windows 95",
		"Windows 98",
		"biz360.com",
		"xpymep",
		"TurnitinBot",
		"sindice",
		"Purebot",
		"libwww-perl",
	}
)