language: node_js
os:
  - linux
node_js: 10
cache: yarn

branches:
  only:
    - master

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - yarn
  - ./yarn_build.sh

after_success:
  - mv docs /tmp/docs
  - rm -rf --interactive=never * && rm -rf --interactive=never .[a-zA-Z_-]*
  - mv /tmp/docs/* .

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  repo: methw/web
  target_branch: master
  fqdn: methw.org